# Generated by Django 5.0.2 on 2024-02-28 14:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("movies", "0005_actor"),
    ]

    operations = [
        migrations.AlterField(
            model_name="movie",
            name="mainactor",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="movies.actor",
            ),
        ),
    ]
